"use client";

import React, { useEffect, useState } from 'react';
import { Handle, Position, NodeProps } from 'reactflow';
import { Cpu, Settings2, Loader2, Maximize2, Play } from 'lucide-react';
import { NodeShell } from './NodeShell';
import { GeneratedImageModal } from './GeneratedImageModal';
import { useWorkflowStore } from '@/store/useWorkflowStore';
import { useApiTokenStore } from '@/store/useApiTokenStore';
import { useWorkflowExecution } from '@/hooks/useWorkflowExecution';
import { getAvailableModels, getModelDefinition, type Provider } from '@/lib/models';

export const LLMNode = ({ id, data, selected }: NodeProps) => {
  const updateNodeData = useWorkflowStore((state) => state.updateNodeData);
  const tokens = useApiTokenStore((state) => state.tokens);
  const { runNode } = useWorkflowExecution();
  const [previewOpen, setPreviewOpen] = useState(false);

  // BYOK only: a provider is configured iff the user has saved a key for it.
  const configuredProviders: Provider[] = [];
  if (tokens.gemini) configuredProviders.push('gemini');
  if (tokens.openai) configuredProviders.push('openai');

  const availableModels = getAvailableModels(configuredProviders);
  const modelsByProvider = configuredProviders.map(p => ({
    provider: p,
    label: p === 'gemini' ? 'Google Gemini' : 'OpenAI',
    models: availableModels.filter(m => m.provider === p),
  }));

  // Keep `data.model` in sync with what the dropdown visibly defaults to.
  // Without this, users see one model in the picker but the execution hook
  // falls back to a different model on Run because data.model was never
  // explicitly written. Also prune any saved data.model that's no longer in
  // the registry (e.g. a deprecated model id from an older session).
  useEffect(() => {
    const firstAvailable = availableModels[0]?.id;
    const savedIsValid =
      data.model && availableModels.some((m) => m.id === data.model);
    if (!savedIsValid && firstAvailable) {
      updateNodeData(id, { model: firstAvailable });
    }
  }, [data.model, availableModels, id, updateNodeData]);

  const selectedModel = getModelDefinition(data.model);
  const altText = selectedModel
    ? `Image generated by ${selectedModel.name}${data.systemPrompt ? `: ${String(data.systemPrompt).slice(0, 80)}` : ''}`
    : 'Generated image';

  return (
    <div className="relative">
      <Handle
        type="target"
        position={Position.Left}
        className="!w-3 !h-3 !bg-primary border-2 border-primary !-left-1.5"
      />

      <NodeShell title="Generate Image" icon={Cpu} iconColor="text-purple-500" selected={selected}>
        <div className="flex flex-col gap-4">
          <div className="space-y-2">
            <div className="flex items-center gap-1.5">
              <Settings2 size={12} className="text-gray-400" />
              <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Image Model Selector</label>
            </div>
            {availableModels.length > 0 ? (
              <select
                value={data.model || availableModels[0]?.id || ''}
                onChange={(e) => updateNodeData(id, { model: e.target.value })}
                className="w-full p-2.5 rounded-xl bg-gray-50 border border-node-border text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 transition-all appearance-none cursor-pointer"
              >
                {modelsByProvider.map((group) => (
                  <optgroup key={group.provider} label={group.label}>
                    {group.models.map((m) => (
                      <option key={m.id} value={m.id}>{m.name}</option>
                    ))}
                  </optgroup>
                ))}
              </select>
            ) : (
              <div className="p-2.5 rounded-xl bg-yellow-50 border border-yellow-200 text-xs text-yellow-700">
                No API keys configured. Open Settings to add one.
              </div>
            )}
          </div>

          <div className="space-y-2">
            <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">System Prompt (Optional)</label>
            <textarea
              className="w-full min-h-[80px] p-3 rounded-xl bg-gray-50 border border-node-border text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 resize-none transition-all"
              placeholder="You are a helpful assistant..."
              value={data.systemPrompt || ''}
              onChange={(e) => updateNodeData(id, { systemPrompt: e.target.value })}
            />
          </div>

          <button
            type="button"
            onClick={() => runNode(id)}
            disabled={!!data.loading || availableModels.length === 0}
            aria-busy={!!data.loading}
            className="flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-white shadow-sm shadow-primary/20 transition-all hover:bg-primary/90 active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-60 disabled:active:scale-100 disabled:hover:bg-primary"
          >
            {data.loading ? (
              <>
                <Loader2 size={14} className="animate-spin" aria-hidden="true" />
                Running…
              </>
            ) : (
              <>
                <Play size={14} fill="white" aria-hidden="true" />
                Run this node
              </>
            )}
          </button>

          <div className="pt-2">
            <div className={`p-3 rounded-xl border flex flex-col gap-2 transition-all ${data.error ? 'bg-red-50 border-red-100' : 'bg-primary/5 border-primary/10'}`}>
              <div className="flex items-center justify-between">
                <span className={`text-[10px] font-bold uppercase tracking-widest ${data.error ? 'text-red-500' : 'text-primary'}`}>
                  {data.error ? 'Error' : 'Output'}
                </span>
                {data.loading && <Loader2 size={12} className="text-primary animate-spin" />}
              </div>
              <div className="text-xs min-h-[40px] font-medium leading-relaxed">
                {data.error ? (
                  <span className="text-red-600">{data.error}</span>
                ) : data.value ? (
                  <button
                    type="button"
                    onClick={() => setPreviewOpen(true)}
                    className="group relative block w-full cursor-zoom-in overflow-hidden rounded-lg border border-primary/10"
                    aria-label="Open generated image preview"
                  >
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={data.value}
                      alt={altText}
                      className="block h-auto max-h-[200px] w-full object-contain"
                    />
                    <span className="pointer-events-none absolute inset-0 flex items-center justify-center bg-black/0 transition-colors group-hover:bg-black/30">
                      <span className="grid h-9 w-9 place-items-center rounded-full bg-white/90 text-gray-700 opacity-0 shadow-md transition-opacity group-hover:opacity-100">
                        <Maximize2 size={14} aria-hidden="true" />
                      </span>
                    </span>
                  </button>
                ) : (
                  <span className="text-gray-400 italic">
                    {data.loading ? 'Generating image...' : 'Image will appear here'}
                  </span>
                )}
              </div>
            </div>
          </div>
        </div>
      </NodeShell>

      <Handle
        type="source"
        position={Position.Right}
        className="!w-3 !h-3 !bg-primary border-2 border-primary !-right-1.5"
      />

      {previewOpen && data.value && (
        <GeneratedImageModal
          src={data.value}
          alt={altText}
          onClose={() => setPreviewOpen(false)}
        />
      )}
    </div>
  );
};
